# Generated by Django 2.2.8 on 2020-07-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(default=1)),
                ('active', models.SmallIntegerField(default=1)),
                ('two_step_varification', models.SmallIntegerField(default=0)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('role', models.IntegerField()),
                ('api_token', models.CharField(blank=True, max_length=60, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
