# Generated by Django 2.2.8 on 2020-07-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_identifier', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('lookup_value', models.CharField(max_length=255)),
                ('parent_lookup', models.BigIntegerField(null=True)),
            ],
        ),
    ]
