# Generated by Django 2.2.8 on 2020-07-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=191)),
                ('branch_name', models.CharField(max_length=191)),
                ('parent_id', models.IntegerField(default=0, null=True)),
                ('type', models.IntegerField()),
                ('city', models.CharField(max_length=191)),
                ('state', models.CharField(max_length=191)),
                ('country', models.CharField(max_length=191)),
                ('branch_code', models.CharField(default=1, max_length=191)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
